---
name: Complementary config test

on:
  pull_request:
    branches:
        - 'master'
    paths:
      - '**'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'
      - '!datacube_ows/__init__.py'
      - '!.github/**'
      - '.github/workflows/complementary-config-test.yaml'

  push:
    branches:
      - 'master'
    paths:
      - '**'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'
      - '!datacube_ows/__init__.py'
      - '!.github/**'
      - '.github/workflows/complementary-config-test.yaml'

env:
  ORG: opendatacube
  IMAGE: ows

jobs:
  dea-config:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout ows
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: datacube-ows

      - name: git checkout dea-config
        uses: actions/checkout@v2
        with:
          repository: GeoscienceAustralia/dea-config
          path: dea-config

      - name: Build dev OWS image
        run: |
          cd ./datacube-ows
          docker build \
            --tag    ${ORG}/${IMAGE}:_builder \
            .

      - name: Config parser check
        run: |
          cd ./datacube-ows
          export $(grep -v '^#' ./complementary_config_test/.env_complementary_config_dea_dev | xargs)
          env
          docker-compose -f docker-compose.yaml -f docker-compose.db.yaml up -d
          docker-compose -f docker-compose.yaml -f docker-compose.db.yaml exec -T ows /bin/sh -c "env; datacube system check"
          docker-compose -f docker-compose.yaml -f docker-compose.db.yaml exec -T ows /bin/sh -c "curl https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/services/wms/inventory.json -o /tmp/inventory.json"
          docker-compose -f docker-compose.yaml -f docker-compose.db.yaml exec -T ows /bin/sh -c "cd /code; ./compare-cfg.sh"
          docker-compose -f docker-compose.yaml -f docker-compose.db.yaml down
