---
name: Tests

on:
  pull_request:
    branches:
        - 'master'
    paths:
      - '**'
      - '.github/workflows/deaconfig-integration.yaml'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'
      - '!datacube_ows/__init__.py'
      - '!.github/**'

  push:
    branches:
      - 'master'
    paths:
      - '**'
      - '.github/workflows/deaconfig-integration.yaml'
      - '!docs/**'
      - '!*.rst'
      - '!*.md'
      - '!datacube_ows/__init__.py'
      - '!.github/**'

env:
  ORG: opendatacube
  IMAGE: ows
  DB_USERNAME: opendatacubeusername

jobs:
  unit-integration-performance-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repo: GeoscienceAustralia/dea-config
          path: ~/

      # We build the stage 1 image, then run test on it
      # These tests require extra files we don't want in
      # the production image
      # We build the stage 1 image, then run test on it
      # These tests require extra files we don't want in
      # the production image
      - name: Build dev OWS image (stage 1 - unit test builder)
        run: |
          docker build \
            --tag    ${ORG}/${IMAGE}:_builder \
            .

      - name: Dockerized Integration Pytest (stage 1 - integration test)
        run: |
          chmod a+rw artifacts
          export $(grep -v '^#' .env_ows_root | xargs)
          docker-compose -f docker-compose.yaml -f docker-compose.db.yaml up -d
          docker-compose -f docker-compose.yaml -f docker-compose.db.yaml exec -T ows /bin/sh -c "wget https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/services/wms/inventory.json -O /env/config/ows_refactored/inventory.json; datacube-ows-cfg check -i /env/config/ows_refactored/inventory.json"
          docker-compose -f docker-compose.yaml -f docker-compose.db.yaml down
