---
name: Pyspellcheck

on:
  pull_request:
    branches:
      - 'master'

  push:
    branches:
      - 'master'

jobs:
  pyspellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: igsekor/pyspelling-any@v0.0.2
        name: Spellcheck
