---
name: Pyspellcheck

on:
  pull_request:
    branches:
        - 'master'
    paths:
      - 'docs/**'
      - '*.md'

  push:
    branches:
      - 'master'
    paths:
      - 'docs/**'
      - '*.md'

jobs:

  pyspellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: igsekor/pyspelling-any@v0.0.2
        name: Spellcheck
